version: "3.3"
services:
  jupyter:
    image: jupyter:1.2
    build: .
    ports:
      - "1111:1111"
    volumes:
      - myapp:/home/
      - data_folder:/home/data/
volumes:
  myapp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data 
  data_folder:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/davidkuchelmeister/Documents/Projects_Coding/data
